# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('distancia', models.IntegerField()),
                ('clase', models.CharField(choices=[('PERRO', 'PERRO'), ('GATO', 'GATO')], max_length=50)),
            ],
        ),
    ]
